# Generated by Django 5.0.2 on 2024-02-21 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightmandu', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
