# Generated by Django 5.0.2 on 2024-02-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightmandu', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userFname', models.CharField(max_length=100)),
                ('userLname', models.CharField(max_length=100)),
                ('userDob', models.DateField()),
                ('userEmail', models.EmailField(max_length=254, unique=True)),
                ('userPhone', models.CharField(max_length=20)),
                ('userPassword', models.CharField(max_length=128)),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
