# Generated by Django 5.0.2 on 2024-02-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightmandu', '0004_userprofile_delete_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userFname', models.CharField(max_length=100)),
                ('userLname', models.CharField(max_length=100)),
                ('userDob', models.DateField()),
                ('userEmail', models.EmailField(max_length=254)),
                ('userPhone', models.CharField(max_length=15)),
                ('userPassword', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
