# Generated by Django 5.0.2 on 2024-02-22 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightmandu', '0005_customerinfo_delete_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerInfo',
        ),
    ]
